<div ng-controller="auth">
    <form ng-submit="login(user)">
        <table>
            <tr>
                <td>login: </td>
                <td><input type="text" ng-model="user.login"></td>
            </tr>
            <tr>
                <td>password: </td>
                <td><input type="text" ng-model="user.password"> <br/></td>
            </tr>
            <tr>
                <td>Remember me: </td>
                <td><input type="checkbox" ng-model="user.rememberMe"> <br/></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit"></td>
            </tr>
        </table>
    </form>
</div>

